In [1]:
# Creating Numpy arrays
import numpy as np

# Converting from a list
#Lets start with a list

my_list1 = [1,2,3,4]

my_array1 = np.array(my_list1)



In [2]:
#Print out array
print(my_array1)
# my_array

[1 2 3 4]


In [3]:
# Make another list
my_list2 = [11,22,33,44]

#Make a list of lists
my_lists = [my_list1,my_list2]

#Make multi-dimensional array
my_array2 = np.array(my_lists)

#Show array
my_array2

array([[ 1,  2,  3,  4],
       [11, 22, 33, 44]])

In [5]:
#Lets get the size of the array
my_array2.shape

(2, 4)

In [6]:
#Find out the data type of the array
my_array2.dtype

dtype('int32')

In [7]:
#Making special case arrays

#Zeros
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
#Ones
array3=np.ones(5)
array3.dtype

dtype('float64')

In [18]:
# An empty array
np.empty(5)

array([1., 1., 1., 1., 1.])

In [19]:
#Identity array
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
# Using a range

np.arange(5)

array([0, 1, 2, 3, 4])

In [21]:
np.arange(5,50,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])