In [1]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

In [7]:
# WE can randomly reorder (permutate) a Series, or the rows in a DataFrame

#Let's take a look
dframe = DataFrame(np.arange(16).reshape((4, 4)))

#Create an array with a random perumation of 0,1,2,3
blender=np.random.permutation(4)
blender

array([1, 0, 3, 2])

In [5]:
dframe

0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [8]:
# Now permutate the dframe based on the blender
dframe.take(blender)

0   1   2   3
1   4   5   6   7
0   0   1   2   3
3  12  13  14  15
2   8   9  10  11

In [2]:
# Now what if we want permuations WITH replacement

In [9]:
# Let imagine a box with 3 marbles in it: labeled 1, 2, and 3

box=np.random.permutation([1,2,3])
# Now lets create a random permuation WITH replacement using randint
shaker=np.random.randint(0,len(box),size=10)

In [10]:
# Let's check teh box "shaker"
shaker

array([2, 2, 0, 2, 2, 2, 2, 2, 0, 0])

In [11]:
#Now lets grab form the box
hand_grabs=box.take(shaker)

#show
hand_grabs

array([3, 3, 1, 3, 3, 3, 3, 3, 1, 1])

Congratulations! We're all done with this Section.
Up next: Working with Data Part 3 !!!