In [1]:
import numpy as np



In [2]:
#Create an array
arr = np.arange(5)

In [13]:
#Saving array on disk in binary format (file extension .npy)
np.save('my_array',arr)

In [14]:
#Change arr
arr2 = np.arange(10)
#Show
arr

array([0, 1, 2, 3, 4])

In [15]:
#Lets see the original saved copy
np.load('my_array.npy')

array([0, 1, 2, 3, 4])

In [16]:
#Saving multiple arrays into a zip file
np.savez('two_arrays.npz',x=arr,y=arr2)

In [17]:
#Now loading multiple arrays
archive_array = np.load('two_arrays.npz')

#Show
archive_array['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
#Now saving and loading text files

arr = np.array([[1,2,3],[4,5,6]])
np.savetxt('my_test_text.txt',arr,delimiter=',')

In [22]:
arr = np.loadtxt('my_test_text.txt',delimiter = ',')
arr


array([[1., 2., 3.],
       [4., 5., 6.]])