In [1]:
import numpy as np

# Universal functions perform operations on all elements in an array

In [2]:
arr = np.arange(11)

arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
#Taking Square Roots
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [4]:
#Calcualting exponential (e^)
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [5]:
# Binary Functions require two arrays

#Random array (normal dist)
A = np.random.randn(10)

A


array([-0.17099919,  1.70170884,  2.58552148,  0.44050336, -1.72640388,
        0.26064608,  2.08450248, -0.1912407 ,  0.23166048, -1.11811027])

In [6]:
#Random array (normal dist)
B = np.random.randn(10)
B

array([ 2.26571938, -1.39297608, -0.87580421, -1.79722493,  1.61169359,
       -0.48843104,  0.56103614,  1.32688697,  0.15844371,  1.55585256])

In [7]:
#Addition
np.add(A,B)

array([ 2.0947202 ,  0.30873276,  1.70971727, -1.35672156, -0.1147103 ,
       -0.22778496,  2.64553862,  1.13564628,  0.39010419,  0.43774229])

In [8]:
#Finding max or min between two arrays
np.maximum(A,B)

array([2.26571938, 1.70170884, 2.58552148, 0.44050336, 1.61169359,
       0.26064608, 2.08450248, 1.32688697, 0.23166048, 1.55585256])

In [9]:
#For full and extensive list of all universal functions
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True